name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        crystal: [0.34.0, latest, nightly]    
    
    container:
      image: crystallang/crystal:{{ matrix.crystal }}

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
